### ISSUE TITLE
Sync movement of Code and Preview 

### ISSUE THREAD

**Issue by ramlaxman** [gwillz/slides#2]
It will be nice if you can add this feature of VScode. 

As code moves, so the preview of it.

**Comment by gwillz** [comment]
Hmm. I see what you mean - it's a cool feature.

Obviously it's possible. I'm trying to imagine how I'll achieve it here.

A few notes:
- the VSCode markdown preview is rendered live, unlike here.
- we have floating images, which could change the method used by VSCode a fair bit.
- the horizontal rules define a fixed height per slide, this is additional complexity (or less..?)

I think I can make a compromise where, on render, the preview will scroll to the current slide. The 'current slide' being wherever the cursor is within the editor. What do you think?

I think this solution is good because it's little effort and little complexity with the same results.

**Comment by ramlaxman** [comment]
Or on the other side of coin, you can do it sectiowise i.e. slidewise. 
IMO, VScode renders area wise i.e. portion fits in Full size window.
On contrary of it, you can go slidewise so that it will put less stress on rendering as per my observation.

**Comment by gwillz** [comment]
Yeah that's interesting.

My concern is complexity, not performance. I'm apprehensive to include fully-synchronised scrolling because I've seen other attempts go quite badly. Most solutions that I can immediately see introduce a lot of edge-cases.

I've got a few ideas. I've pushed the first part already. I'll include live rendering soon I think.

**Comment by gwillz** [comment]
Okay cool it's done.

It now live renders and scrolls to the 'last rendered slide'. In 99% of cases, this is the same slide as the one currently being edited.

I guess if you typed _really really fast_ and across multiple slides, it'll scroll to the bottom edited slide.

See what you think.

**Comment by ramlaxman** [comment]
I used and loved it. The implementation that I liked is only after edit is complete, it moves to preview. Hmm.. thoughtful !
